#!/bin/sh
# build-answerfile.sh — generate a setup-alpine answerfile for a fully
# non-interactive disk install, to run over the first-boot SSH session that
# build-apkovl.sh gets you.
#
# What it does: writes every *OPTS variable setup-alpine needs to get through
# keymap/hostname/interfaces/dns/timezone/proxy/ntp/apkrepos/user/sshd/disk
# without a single interactive prompt. See lessons-learned.md ("setup-alpine
# (step 6) full CLI automation") for exactly why each of these values is what
# it is — several of setup-alpine's defaults are real footguns (e.g. -q skips
# the disk-install step entirely; leaving USEROPTS unset makes it prompt for
# a username) that aren't obvious from its own --help.
#
# Deliberately NOT covered here: WiFi, extra users, app packages — same
# out-of-scope boundary as build-apkovl.sh. This gets you a persistent,
# installed, headless-SSH-accessible Alpine system and stops there.
#
# Usage:
#   sh build-answerfile.sh <hostname> [output-dir] [disk]
#
#   hostname    required — the real hostname for the installed system
#               (build-apkovl.sh deliberately leaves this as "localhost" for
#               the transient first-boot session; this is where it's set for
#               real, per flashing-base-alpine.md)
#   output-dir  defaults to .
#   disk        defaults to /dev/mmcblk0 (the SD card, from the Pi's own
#               point of view — override only if targeting a different disk)
#
# Copy the resulting file to the Pi (e.g. `scp answerfile root@<ip>:/root/`)
# and run, over that SSH session:
#
#   yes | setup-alpine -e -f /root/answerfile
#
# -e empties the root password (the one prompt the answerfile itself can't
# cover). `yes` (not a single `echo y`) answers setup-disk's unavoidable
# erase-confirmation prompt(s) — see lessons-learned.md for why a single
# echo risks a hang.

set -e

HOSTNAME="$1"
OUTDIR="${2:-.}"
DISK="${3:-/dev/mmcblk0}"

if [ -z "$HOSTNAME" ]; then
    echo "Usage: sh build-answerfile.sh <hostname> [output-dir] [disk]" >&2
    exit 1
fi
if [ ! -d "$OUTDIR" ]; then
    echo "Output dir not found: $OUTDIR" >&2
    exit 1
fi
OUTDIR=$(cd "$OUTDIR" && pwd)

OUTFILE="$OUTDIR/answerfile"

cat > "$OUTFILE" <<EOF
# Generated by build-answerfile.sh — see lessons-learned.md for why each of
# these values is what it is before hand-editing.

KEYMAPOPTS=none

HOSTNAMEOPTS="$HOSTNAME"

DEVDOPTS=mdev

# Leave whatever build-apkovl.sh already configured for eth0 alone. Re-running
# setup-interfaces against a live directly-cabled SSH session risks disrupting
# the very connection you're running this command over.
INTERFACESOPTS=none

# setup-dns only skips itself when /etc/network/interfaces already has a dhcp
# line — otherwise it always runs, and with no args it prompts interactively
# for both domain and nameservers. This is a placeholder for the static-IP
# case (no real DNS on a direct-cable link); edit if you need it to resolve
# anything real.
DNSOPTS="-d lan 1.1.1.1 8.8.8.8"

TIMEZONEOPTS=UTC

PROXYOPTS=none

# Auto-picks the first mirror (a CDN) without probing for speed. Requires
# internet access to fetch the mirror list — on an offline direct-cable link
# this fails quietly (leaves /etc/apk/repositories unconfigured) rather than
# hanging or blocking the rest of the install. Fine to leave broken for
# milestone 1; fix it later once the Pi has real internet.
APKREPOSOPTS="-1"

# Must be exactly "none" with no other flags — setup-user special-cases this
# to skip cleanly. Leaving USEROPTS unset makes setup-alpine fall back to
# "-a -g audio,input,video,netdev" with no username, which prompts
# interactively. This repo is root-only by design; add a user afterward, over
# SSH, if a specific project needs one.
USEROPTS=none

# ROOTSSHKEY deliberately left unset: build-apkovl.sh's authorized_keys is
# already in place and correct (root-owned, right permissions) by the time
# this runs. setup-sshd only appends a key if -k/ROOTSSHKEY is given, so
# leaving it unset means it's left alone.
SSHDOPTS=openssh

NTPOPTS=none

DISKOPTS="-m sys $DISK"

LBUOPTS=none
APKCACHEOPTS=none
EOF

echo "==> Wrote $OUTFILE"
echo "    Copy it to the Pi and run, over the first-boot SSH session:"
echo "      scp $OUTFILE root@<pi-ip>:/root/answerfile"
echo "      ssh root@<pi-ip> 'yes | setup-alpine -e -f /root/answerfile'"
echo ""
echo "    Not yet confirmed end-to-end against real hardware — see"
echo "    lessons-learned.md before trusting this for a real deployment."
